/**
 * Data structures and schemas for validation system.
 *
 * Defines TypeScript interfaces for structured data throughout the validation pipeline.
 */

import type { FigmaFrameInfo, FrameStructNode } from '../../types/figma-types';

import type { ComponentHistoryEntry, JudgerDiagnosis } from '../../agents/judger-agent/types';
import type { RefinerResult } from '../../agents/refiner-agent/types';
import type { ComponentAggregationData } from '../../tools/position-tool/types';

export type { ComponentHistory, ComponentHistoryEntry, JudgerDiagnosis } from '../../agents/judger-agent/types';
export type { RefinerResult } from '../../agents/refiner-agent/types';
export type { LaunchOptions, LaunchResult, LaunchStage, LaunchAgentResult } from '../../agents/launch-agent/types';
export type { GitCommitOptions, GitCommitResult } from '../../agents/commit-agent/types';
export type { BoundingBox, PositionError, Rectangle, ComponentAggregationData } from '../../tools/position-tool/types';

/**
 * User-facing validation report with annotated screenshots and analysis
 * Generated by ValidationNode after position capture and annotation
 */
export interface UserReport {
    design: {
        snap: string; // Figma thumbnail URL
        markedSnap: string; // Annotated design image (base64 data URI)
    };
    page: {
        url: string; // Local server URL
        snap: string; // Page screenshot (base64 data URI)
        markedSnap: string; // Annotated page screenshot (base64 data URI)
    };
    report: {
        heatmap: string; // Reserved for future heatmap implementation (empty for now)
        detail: {
            metrics: {
                mae: number;
                sae: number;
                misalignedCount: number;
            };
            // Grouped component type for report visualization
            components: {
                componentId: string;
                componentPath: string;
                elementId?: string;
                validationInfo?: {
                    x: number;
                    y: number;
                };
                elements?: {
                    elementId: string;
                    elementIndex: number;
                    validationInfo: {
                        x: number; // Horizontal deviation in px
                        y: number; // Vertical deviation in px
                    };
                }[];
            }[];
        };
    };
}

/**
 * Structured validation error report
 * Contains position comparison data for a single component
 */
export interface ValidationReport {
    /** [x, y] of rendered position */
    currentPosition: [number, number];
    /** [x, y] of expected Figma position */
    targetPosition: [number, number];
    /** [abs_error_x, abs_error_y] absolute values of position error */
    absoluteError: [number, number];
}

/**
 * Single component's correction log
 * Tracks the diagnosis and fix applied to one component in an iteration
 */
export interface ComponentCorrectionLog {
    elementIds: string[];
    componentId: string;
    componentPath: string;
    validationReport: ValidationReport;
    diagnosis?: JudgerDiagnosis;
    refinerResult?: RefinerResult;
    positionHistory?: ComponentHistoryEntry[];
}

/**
 * Skipped element entry
 * Tracks elements that were skipped during validation
 */
export interface SkippedElement {
    elementId: string;
    reason: 'missing_component_mapping' | 'incomplete_data' | 'no_figma_position';
    details?: string;
}

/**
 * Single iteration log
 * Contains all corrections made in one validation-fix iteration
 */
export interface IterationLog {
    iteration: number;
    metrics: {
        mae: number;
        sae: number;
        misalignedCount: number;
    };
    components: ComponentCorrectionLog[];
    screenshotPath: string;
    skippedElements?: SkippedElement[];
}

/**
 * Complete output schema for processed.json
 * Contains all iteration logs and final result
 */
export interface ProcessedOutput {
    iterations: IterationLog[];
    finalResult: {
        success: boolean;
        finalMae: number;
        finalSae: number;
        totalIterations: number;
        misalignedCount: number; // Number of misaligned components in final result
    };
}

/**
 * Misaligned component data
 * Contains all information about a component that needs fixing
 */
export interface MisalignedComponent {
    name: string;
    componentId: string;
    elementIds: string[];
    path: string;
    validationReport: ValidationReport;
    currentX: number;
    currentY: number;
    targetX: number;
    targetY: number;
    currentWidth: number;
    currentHeight: number;
    targetWidth: number;
    targetHeight: number;
    distance: number;
}

/**
 * Component structure map entry
 * Contains parent-child relationship info for a component
 */
export interface ComponentStructureEntry {
    parentElementId: string | null;
    childIndex: number | null;
    elementIds: string[];
}

/**
 * Component structure map
 * Maps component IDs to their structure information
 */
export type ComponentStructureMap = Record<string, ComponentStructureEntry>;

/**
 * Figma layout metadata
 * Layout properties extracted from Figma JSON for agent reasoning
 */
export interface FigmaLayoutMetadata {
    layoutMode: string;
    primaryAxisAlignItems: string;
    counterAxisAlignItems: string;
    itemSpacing: number;
    padding: {
        top: number;
        right: number;
        bottom: number;
        left: number;
    };
    constraints: Record<string, unknown>;
    absoluteBoundingBox: {
        x?: number;
        y?: number;
        width?: number;
        height?: number;
    };
}

/**
 * Validation loop parameters
 * Direct parameters passed to validationLoop function (NOT through LangGraph state)
 */
export interface ValidationLoopParams {
    figmaJson: FigmaFrameInfo;
    structureTree: FrameStructNode;
    serverUrl?: string;
    figmaThumbnailUrl: string;
    outputDir: string;
    workspaceDir?: string;
    config?: Partial<ValidationLoopConfig>;
    /** Dev server run command (e.g. "pnpm dev"). Required for launch orchestration. */
    runCommand?: string;
    /** Build command (e.g. "pnpm build"). Required for launch orchestration. */
    buildCommand?: string;
}

/**
 * Validation loop configuration
 * Configuration options for the validation loop
 */
export interface ValidationLoopConfig {
    maxIterations: number;
    targetMae: number;
    positionThreshold: number;
    browserTimeout: number;
    defaultViewportWidth: number;
    defaultViewportHeight: number;
    headless: boolean;
    /**
     * Validation execution mode.
     * - reportOnly: run a single validation pass and generate a report (no code edits).
     * - full: run iterative actor-critic refinement loop (may edit code + commit markers).
     */
    mode?: 'reportOnly' | 'full';
    /** Max build attempts with LaunchAgent assistance during validation. */
    maxLaunchBuildAttempts: number;
    /** Max runtime check attempts with LaunchAgent assistance. */
    maxLaunchRuntimeAttempts: number;
}

/**
 * Validation loop result
 * Result returned from validationLoop function
 */
export interface ValidationLoopResult {
    reportGenerated: boolean; // Whether a validation report was successfully generated
    validationPassed: boolean; // Whether validation criteria met (MAE threshold + no errors)
    finalMae: number;
    finalSae: number;
    totalIterations: number;
    processedOutput: ProcessedOutput;
    /** Error message if validation failed due to launch/build issues. */
    error?: string;
    userReport: UserReport;
}

/**
 * Validation result returned from runValidation node
 * Used for both graph workflow and standalone CLI invocation
 */
export interface ValidationResult {
    validationPassed: boolean;
    reportDir: string;
    reportHtmlPath: string;
}

/**
 * Component data aggregation for multiple elements.
 */
export interface ComponentData extends ComponentAggregationData {
    componentId: string;
    componentName: string;
    componentPath: string;
    elementIds: string[];
    errors: { x: number; y: number }[];
}
